[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fair-models"
version = "0.0.1"
description = "Collection of GeoAI Models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8", # zenml needs matplotlib for visualizatoin of charts
    "pyarrow>=23.0.1", # zenml needs pyarrow to pickle the dfs efficiently
    "pystac>=1.14.3",
]

[tool.hatch.build.targets.wheel]
packages = ["fair_integrations"]

[tool.uv.sources]
torchgeo = { git = "https://github.com/kshitijrajsharma/torchgeo.git", rev = "feature/opeanaerialmap" }

[dependency-groups]
dev = [
    "mypy>=1.19.1",
]
local = [
    "zenml[local,server]>=0.93.3", # uv support is added after this release
]
example = [
    "matplotlib>=3.10.8",
    "torchgeo",
]

[project.entry-points."zenml.flavors"]
stac_model_registry = "fair_integrations.registry.flavor:STACModelRegistryFlavor"
