apiVersion: v1
kind: ConfigMap
metadata:
  name: zenml-config
  namespace: fair
  labels:
    app: zenml
data:
  ZENML_STORE_URL: "postgresql://postgres:postgres@postgres.fair.svc:5432/zenml"
  ZENML_SERVER_AUTO_ACTIVATE: "1"
