apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenml
  namespace: fair
  labels:
    app: zenml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenml
  template:
    metadata:
      labels:
        app: zenml
    spec:
      containers:
        - name: zenml
          image: ghcr.io/hotosm/zenml-postgres:0.93.3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: zenml-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
