model:
  name: "example-unet-finetuned-banepa"

parameters:
  base_model_weights: "torchgeo.models.Unet_Weights.OAM_RGB_RESNET50_TCD"
  dataset_chips: "data/banepa/oam/"
  dataset_labels: "data/banepa/osm/"
  epochs: 1
  batch_size: 4
  learning_rate: 0.0001
  weight_decay: 0.0001
  chip_size: 512
  num_classes: 2
